### ISSUE TITLE
cfg has no attributes called 'SWINBLO' and 'lang_adap_mlp'

### ISSUE THREAD

**Issue by thaomaidang** [wuyongjianCODE/VLPMNuD#3]
When running the command `"python tools/test_grounding_net_wuap.py --config-file configs/pretrain/glip_Swin_L.yaml --weight glip_large_model.pth --prompt 'rectangular black nuclei. circle black nuclei. spherical black nuclei. rectangular dark purple nuclei. circle dark purple nuclei. spherical dark purple nuclei.' TEST.IMS_PER_BATCH 1 MODEL.DYHEAD.SCORE_AGG "MEAN" TEST.EVAL_TASK detection MODEL.DYHEAD.FUSE_CONFIG.MLM_LOSS False OUTPUT_DIR OUTPUT" to generate the raw GLIP prediction result, there is an error in swint.py line 701: "adap_mlp=cfg.SWINBO"`. This means 'cfg' has no attribute called SWINBO.

Despite searching your GitHub repository, I was unable to locate any source code defining 'SWINBLO'. Consequently, I tried assigning the value 'adap_mlp=3' to see the outcome. There is an error in bert_model.py line 56: "if cfg.lang_adap_mlp". This means that 'cfg' lacks an attribute called 'lang_adap_mlp'.

In the optional section of your GitHub, a command is provided `"python tools/train_net.py --config-file configs/pretrain/glip_Swin_L.yaml --train_label "/data2/wyj/GLIP/DATASET/coco/annotations/instances_train2017_0166.json" --restart True --use-tensorboard --override_output_dir OUTPUT_TRAIN_fanew MODEL.BACKBONE.FREEZE_CONV_BODY_AT 1 SOLVER.IMS_PER_BATCH 1 SOLVER.USE_AMP True SOLVER.MAX_ITER 500 TEST.DURING_TRAINING True TEST.IMS_PER_BATCH 1 SOLVER.FIND_UNUSED_PARAMETERS False SOLVER.BASE_LR 0.00001 SOLVER.LANG_LR 0.00001 DATASETS.DISABLE_SHUFFLE True MODEL.DYHEAD.SCORE_AGG "MEAN" TEST.EVAL_TASK detection AUGMENT.MULT_MIN_SIZE_TRAIN (800,) SOLVER.CHECKPOINT_PERIOD 100 SWINBLO 3 lang_adap_mlp 2"`, which mentions 'SWINBLO' and 'lang_adap_mlp'.

Could you please guide me on how to resolve these issues? For ease of understanding, I have attached two images. 
Many thanks.

![1](https://github.com/wuyongjianCODE/VLPMNuD/assets/38590744/9824a721-0663-4b87-a33f-239426bcc2ac)
![2](https://github.com/wuyongjianCODE/VLPMNuD/assets/38590744/ad1d9685-54b2-4fe4-a1f7-9cef8b5930ee)

**Comment by wuyongjianCODE** [comment]
please add several lines to file sick/GLIP/maskrcnn_benchmark/config/defaults.py :
_C.SWINBLO = 0
_C.lang_adap_mlp = 0

Reason : when we need to implement some additional features, we will modify this file by adding some new key-value pairs. Since the feature you are currently running is relatively new, the old configuration file has not been updated to include this key, so just add this key and it should work.

**Comment by thaomaidang** [comment]
Thank you so much for your prompt reply; it was helpful. After running the analysis, I obtained the following result: In my case, the mAP (mean Average Precision) of the raw GLIP model is 1.55. Is this correct?

![Screenshot from 2024-01-15 15-27-33](https://github.com/wuyongjianCODE/VLPMNuD/assets/38590744/41ddfeef-a62f-40d4-b514-7408a2d3ebc7)

**Comment by wuyongjianCODE** [comment]
This score is 0.155 = 15.5%. It works well. As I mentioned in README.md , "Normally, the mAP score of raw glip should be in the range [0.15, 0.2]. Then you can use the predicted result (i.e. the json file) to run a self-training algorithm, and you will get a near SOTA score (range [0.4, 0.45])."

**Comment by thaomaidang** [comment]
Thank you so much for your prompt reply !!!

**Comment by thaomaidang** [comment]
Thank you so much for your prompt reply !!! I will close this issue =))
