### ISSUE TITLE
Incompatible sizes of tensori and self.my_fc(tensori)

### ISSUE THREAD

**Issue by thaomaidang** [wuyongjianCODE/VLPMNuD#4]
Hello,

If we train the raw GLIP, the size of both tensori and self.my_fc(tensori) are 12544; however, self-Training GLIP using generated raw GLIP prediction code raised an error as following:

When running the provided command `python tools/train_net.py --config-file configs/pretrain/glip_Swin_L.yaml --train_label "DATASET/coco/annotations/instances_train2017_0166.json" --restart True --use-tensorboard 
--override_output_dir OUTPUT_TRAIN_fanew MODEL.BACKBONE.FREEZE_CONV_BODY_AT 1 SOLVER.IMS_PER_BATCH 1 SOLVER.USE_AMP True SOLVER.MAX_EPOCH 4 TEST.DURING_TRAINING True TEST.IMS_PER_BATCH 1 SOLVER.FIND_UNUSED_PARAMETERS False SOLVER.BASE_LR 0.00001 SOLVER.LANG_LR 0.00001 DATASETS.DISABLE_SHUFFLE True MODEL.DYHEAD.SCORE_AGG "MEAN" TEST.EVAL_TASK detection AUGMENT.MULT_MIN_SIZE_TRAIN (800,) SOLVER.CHECKPOINT_PERIOD 100`, there is the error in generalized_vl_rcnn.py. 

I printed out the size of both tensori and self.my_fc(tensori) to make it easier for you to understand.
![screenshot](https://github.com/wuyongjianCODE/VLPMNuD/assets/38590744/e1d8e496-877d-4038-ab73-15e62d130e18)

**Comment by wuyongjianCODE** [comment]
According to the command you used, in that config, cfg.generalized_vl should be 0. Make sure about this. This error will come out only when you use cfg.generalized_vl > 0. How to check: 1.try search 'generalized_vl = 1', find where is wrong. OR 2.edit the config "defaults.py",add key _C.generalized_vl = 0.

But generalized_vl = 1 meaning a new feature, which I wish it works for other users. Are you using your custom dataset?

**Comment by wuyongjianCODE** [comment]
Wait. In my project, the tensori always and should be shape 256 * 7 * 7 =12544. Then the my_fc layer can work well. Why your tensori here is 12800, is it shape 256 * 50 or 128 * 10 * 10?

**Comment by thaomaidang** [comment]
I did not change any settings and used the provided dataset in DATASET/coco.

**Comment by thaomaidang** [comment]
Before running `flatten()` function, the size of tensori is `torch.Size([2, 256, 5, 5])`.

**Comment by wuyongjianCODE** [comment]
I have updated the generalized_vl_rcnn.py today. Now the key generalized_vl = 0 by default. Download it and I suppose it will work now

**Comment by thaomaidang** [comment]
> I have updated the generalized_vl_rcnn.py today. Now the key generalized_vl = 0 by default. Download it and I suppose it will work now

I really appreciate your prompt reply, your time, and your expertise. 

After using your updated file, I encountered a 'CUDA run out of memory' problem. I am using one TITAN Xp, which has 11GB of memory, while you used four Nvidia RTX 3090s, each with 24GB of memory. I think the problem occurred because I do not have enough GPU capacity. Is there any way to train your model using just one or two GPUs? 

Thank you so much again =))

**Comment by wuyongjianCODE** [comment]
I ever tried smaller gpus before.It need about 16G memory to run .Each gpu must bigger than 16G! for example, one 24G gpu works ; two 12G gpu can not work. So, you can not "train" GLIP, you can only do "infer"( you have got score 0.155 via "infer").But, you can choose YOLOX to do self-training instead, as I mentioned in README.

**Comment by thaomaidang** [comment]
Thank you for your sharing. I will try YOLOX =)) Many thanks
