### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by thaomaidang** [wuyongjianCODE/VLPMNuD#5]
Hello,

I have a question: Did you use the prompt  `--prompt 'rectangular black nuclei. circle black nuclei. spherical black nuclei. rectangular dark purple nuclei. circle dark purple nuclei. spherical dark purple nuclei.'` throughout the entire project without changing it?

I noticed in your cautionary note that the prompt section would be updated:

> Caution: --prompt param here gives an example prompt obtained from [blip](to be update)

Could you please upload the final prompt used in this project? I really appreciate your excellent work.

**Comment by wuyongjianCODE** [comment]
That one is an example.
This is the final prompt used but there should be little difference on their performance:
--prompt "round purple nuclei.round black nuclei.round blue nuclei.circle purple nuclei. circle black nuclei.circle blue nuclei. oblong purple nuclei.oblong black nuclei.oblong blue nuclei."

**Comment by thaomaidang** [comment]
Thank you so muchhhhhh
